apiVersion: v1
kind: Namespace
metadata:
  name: {{ .Chart.Name }}
  labels:
    app: {{ template "name" . }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}